name: Build and Release AutoPr    - name: Publish application
      run: dotnet publish AutoPressApp.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Create zip archive
      run: Compress-Archive -Path ./publish/AutoPressApp.exe -DestinationPath ./AutoPressApp-win-x64-single.zip
      shell: powershell
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AutoPressApp-single-exe-${{ github.sha }}
        path: AutoPressApp-win-x64-single.zip
        retention-days: 30n:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'  # 只在推送版本標籤時觸發 (如 v1.0.0)
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Verify .NET installation
      run: dotnet --info
    - name: Restore dependencies
      run: dotnet restore AutoPressApp.csproj --verbosity normal
    - name: Build application
      run: dotnet build AutoPressApp.csproj --configuration Release --no-restore --verbosity normal
    - name: Restore dependencies for publish
      run: dotnet restore AutoPressApp.csproj --runtime win-x64
    - name: Publish application
      run: dotnet publish AutoPressApp.csproj --configuration Release --output ./publish --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Create zip archive
      run: Compress-Archive -Path ./publish/AutoPressApp.exe -DestinationPath ./AutoPressApp-win-x64-single.zip
      shell: powershell
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AutoPressApp-single-exe-${{ github.sha }}
        path: AutoPressApp-win-x64-single.zip
        retention-days: 30
    - name: Get version from tag
      id: get_version
      run: |
        if ($env:GITHUB_REF -match "refs/tags/(.*)") {
          $version = $matches[1]
        } else {
          $version = "dev-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
      shell: powershell
    - name: Create Release and Upload Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: AutoPressApp ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## AutoPressApp Release ${{ steps.get_version.outputs.VERSION }}
          
          ### 下載說明
          - 下載 `AutoPressApp-win-x64-single.zip` 檔案
          - 解壓縮後執行 `AutoPressApp.exe` (單一檔案，無需其他 DLL)
          
          ### 系統需求
          - Windows 10 或更新版本
          - x64 架構
          
          此版本為單一可執行檔，包含所有必要的運行時文件和依賴項。
        files: |
          AutoPressApp-win-x64-single.zip
        draft: false
        prerelease: false
